@echo off
REM AQUI SERA DEFINIDO O TITULO DO SCRIPT (MENOS RELEVANTE)
TITLE BACKUP BASE DE DADOS

REM AQUI IREMOS DEFINIR QUAL SERA A LETRA DA UNIDADE A SER MONTADA PARA RECEBER O BACKUP
set drive=G

REM ALTERE O VALOR ABAIXO PARA O NOME DO VOLUME QUE DESEJA MONTAR
set volume=[DELETE ESSE VALOR AQUI E COLE O RESULTADO QUE APARECER NO COMANDO MOUTNVOL]

echo MONTANDO UNIDADE
mountvol %drive%: %volume%
echo UNIDADE MONTADA!

REM SETANDO OS LOCAIS
REM O ORACLE SID VARIA DE UM BANCO PARA OUTRO, CASO TENHA DUVIDA CONSULTE SEU SYSDBA OU O DESENVOLVEDOR DO SISTEMA
SET ORACLE_SID=ORCL
SET DUMPFILE_FOLDER="c:\copia"
SET DEST_LOG ="C:\log_backup"
SET ARCHIVE_PROGRAM="C:\Program Files\7-Zip\7z.exe"

REM SETANDO DATA E FORMATOS
SET DD=%date:~0,2%
SET MM=%date:~3,2%
SET YYYY=%date:~6,4%
SET T=%TIME: =0%
SET EXPORTDATE=%DATE:~6,4%%DATE:~3,2%%DATE:~0,2% %T:~0,2%%T:~3,2%

REM DEFININDO NOMES
SET BASE_NAME=ARQUIVO_%DD%_%MM%_%YYYY%
SET DUMPFILE_NAME=%BASE_NAME%.dmp
SET LOGFILE_NAME=%BASE_NAME%.log
SET BACKUP_FILENAME=%BASE_NAME%.zip

REM Script begin
REM expdp, backup to "copia"
REM SUBSTITUIA O USUARIO E A SENHA
echo "BACKUP ORACLE"
expdp USUARIO/SENHA directory=copia dumpfile=%DUMPFILE_NAME% logfile=%LOGFILE_NAME%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
echo
REM COMPACTACAO
echo "COMPACTANDO"
%ARCHIVE_PROGRAM% a -tzip %DUMPFILE_FOLDER%\%BACKUP_FILENAME% %DUMPFILE_FOLDER%\%DUMPFILE_NAME% %DUMPFILE_FOLDER%\%LOGFILE_NAME%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR
echo.
REM ESSA ETAPA IRA VERIFICAR SE O DIRETORIO NO HD DE BACKUP EXISTE, CASO NAO EXISTA ELE IRA CRIAR O DIRETORIO PARA RECEBER O ARQUIVO COMPACTADO
echo "VERIFICANDO A PASTA BACKUP"
if not exist G:\backup (mkdir G:\backup) else (echo existe)
echo "COPIANDO ARQUIVOS"
xcopy %DUMPFILE_FOLDER%\%BACKUP_FILENAME% G:\backup /E/Y/C/H/D

REM OS ARQUIVOS COM MAIS DE 7 DIAS SERAO DELETADOS (CASO QUEIRA ALTERAR A QUANTIDADE DE DIAS ALTERE O VALOR DO PARAMETRO D -7 PELA QUANTIDADE DE DIAS QUE VOCE QUER MANTER OS ARQUIVOS
echo "DELETANDO ARQUIVOS COM MAIS DE 7 DIAS"
forfiles /p "G:\backup" /s /m ** /D -7 /C "cmd /c del @path"

REM AQUI IREMOS DELETAR OS ARQUIVOS TEMPORARIOS QUE ESTAO NO DIRETORIO "COPIA" OU O DIRETORIO QUE VOCE DEFINIR PARA A GERACAO DO ARQUIVO DMP
echo "DELETANDO ARQUIVOS TEMPORÁRIOS"
DEL %DUMPFILE_FOLDER%\%DUMPFILE_NAME% /S /Q
DEL %DUMPFILE_FOLDER%\%LOGFILE_NAME% /S /Q
DEL %DUMPFILE_FOLDER%\%BACKUP_FILENAME% /S /Q


REM AQUI ELE IREMOS DESMONTAR O VOLUME
set drive=G:
echo DESMONTANDO UNIDADE
mountvol %drive% /p
echo UNIDADE DESMONTADA!

exit