SET DD=%date:~0,2%
SET MM=%date:~3,2%
SET YYYY=%date:~6,4%
set ftime=%time:~0,2%
set ftime=0%ftime: =%
set ftime=%ftime:~-2%
SET TT=%time:~3,2%
SET EXPORTDATE=%DATE:~6,4%%DATE:~3,2%%DATE:~0,2%%TIME:~0,2%%TIME:~3,2%
REM AQUI VOCE PODE SUBSTITUIR O "ARQUIVO" PELO NOME DA SUA APLICACAO OU ATE MESMO PELO NOME QUE VOCE PREFERIR
SET LOG_NAME=ARQUIVO_%DD%_%MM%_%YYYY%_%ftime%_%TT%.log

@echo off
REM AQUI ELE VAI VERIFICAR SE A PASTA DE LOGS EXISTE, E DELETAR OS LOGS COM MAIS DE 7 DIAS, LEMBRANDO QUE VOCE PODE ALTERAR A QUANTIDADE DE DIAS MUDANDO O VALOR DO "D -7" PELA QUANTIDADE DE DIAS QUE VOCE DESEJA MANTER OS LOGS
if not exist C:\log_backup (mkdir C:\log_backup) else (echo existe)
forfiles /p "c:\log_backup" /s /m ** /D -7 /C "cmd /c del @path"
REM AQUI O CALL VAI CHAMAR O SCRIPT DE BACKUP USANDO A MESMA JANELA DO PROMPT DE COMANDO, O LOCAL DO SCRIPT PODE SER ONDE VOCE PREFERIR
REM POREM VOCE TEM QUE COLOCAR APOS O CALL, POR EXEMPLO "call C:\backup.bat"
call D:\backup.bat >C:\log_backup\%LOG_NAME%
